services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: resume-ranker-app
        container_name: laravel-app-resume-ranker
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            CHOKIDAR_USEPOLLING: true
            APACHE_DOCUMENT_ROOT: /var/www/html/public
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
            mailpit:
                condition: service_started
            selenium:
                condition: service_started
        restart: unless-stopped
    mysql:
        image: 'mysql:8.0'
        container_name: laravel-mysql-resume-ranker
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE:-resume_ranker}'
            MYSQL_USER: '${DB_USERNAME:-user}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        command: '--default-authentication-plugin=mysql_native_password'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD:-secret}'
            retries: 5
            timeout: 10s
        restart: unless-stopped
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        container_name: laravel-phpmyadmin-resume-ranker
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: '${DB_PASSWORD:-secret}'
        networks:
            - sail
        depends_on:
            mysql:
                condition: service_healthy
        restart: unless-stopped
    redis:
        image: 'redis:alpine'
        container_name: laravel-redis-resume-ranker
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 5
            timeout: 10s
        restart: unless-stopped
    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: laravel-mailpit-resume-ranker
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - nc
                - '-z'
                - localhost
                - '1025'
            retries: 3
            timeout: 5s
        restart: unless-stopped
    selenium:
        image: selenium/standalone-chrome
        container_name: laravel-selenium-resume-ranker
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
        restart: unless-stopped
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
