


name: Laravel CI/CD (Windows)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest


    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: resume_ranker_ai
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, xml, ctype, json, curl, bcmath
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set up .env File
        run: Copy-Item .env.example .env

      - name: Configure Database Connection
        run: |
          Add-Content .env "`nDB_CONNECTION=mysql"
          Add-Content .env "`nDB_HOST=127.0.0.1"
          Add-Content .env "`nDB_PORT=3306"
          Add-Content .env "`nDB_DATABASE=resume_ranker_ai"
          Add-Content .env "`nDB_USERNAME=root"
          Add-Content .env "`nDB_PASSWORD=root"

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Storage Permissions
        run: |
          icacls storage /grant "Everyone":(OI)(CI)F /T
          icacls bootstrap/cache /grant "Everyone":(OI)(CI)F /T

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: resume_ranker_ai
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan migrate --force

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: resume_ranker_ai
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test
